export const GET_ADDRESSLIST = 'GET_ADDRESSLIST'
export const GET_ADDRESSONE = 'GET_ADDRESSONE'
export const REMOVE_ADDRESSLIST = 'REMOVE_ADDRESSLIST'
export const UPDATE_ADDRESSLIST = 'UPDATE_ADDRESSLIST'